mode: trainer
ros:
  package: ros
  data_path:
    bags: /Users/sbyim/Workspace/Python/sck-sandbox/pycartracker/data/bags
    cctv: /Users/sbyim/Workspace/Python/sck-sandbox/pycartracker/data/cctv/cctv_positions.xlsx
    videos: /Users/sbyim/Workspace/Python/sck-cartracker/data

trainer:
  name: yolov8_trainer
  dataset:
    dataset_params:
      path: /Users/sbyim/Workspace/Python/sck-cartracker/data/dataset
    dataloader_params:
      batch_size: 64
      shuffle: true

