training_loader:
  batch_size: 128
  shuffle: true
  num_workers: 9
  persistent_workers: true
validation_loader:
  batch_size: 128
  shuffle: false
  num_workers: 9
  persistent_workers: true
test_loader:
  batch_size: 128
  shuffle: false
trainer:
  max_epochs: 10
  # fast_dev_run: true